spring:
  datasource:
    druid:
      filter:
        config:
          enabled: true
      url: jdbc:mysql://10.100.15.50:3306/x_ware_man_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
      username: root
      password: xsmysql

#mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#应用配置
app:
  file-store-path: d:/data/file/