spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev

server:
  port: 8080

app:
  ctx-timeout: 12
  ctx-timeout-unit: HOURS
  avatar-path: avatar/
  scheduled-core-pool-size: 10